//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurcuAslan_Events.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Event_id { get; set; }
        public string Event_name { get; set; }
        public System.DateTime Event_date { get; set; }
        public string Event_desc { get; set; }
        public int City_no { get; set; }
        public string Event_Adress { get; set; }
        public int Capacity { get; set; }
        public int Event_cate_no { get; set; }
        public int User_no { get; set; }
        public bool Event_statu { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Event_categories Event_categories { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
